choco install -y 7zip
choco install -y mingw
choco install -y utorrent
choco install -y cmake
choco install -y clion
choco install -y firefox
choco install -y webstorm
choco install -y git
choco install -y qtcreator
choco install -y python
choco install -y vscode
choco install -y vlc
choco install -y nodejs